### ISSUE TITLE
Internal x/oracle audit

### ISSUE THREAD

**Issue by robert-zaremba** [umee-network/umee#1046] opened 2022-06-21 18:38 UTC
## Summary

We have sync issue and we are investigating from all different fronts where the sync issues comes from.

## Proposal

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment] 2022-07-01 00:51
@robert-zaremba can we close this out, now that we know the sync issue was caused by the price feeder's constant querying?

**Closed** 2022-09-18 22:01 UTC
Labels: C:x/oracle
