### ISSUE TITLE
move github.com/umee-network/umee/v2 to v3

### ISSUE THREAD

**Issue by RafilxTenfen** [umee-network/umee#1271] opened 2022-08-23 22:55 UTC
## Summary of Bug

- When someone imports umeed from v3 tag, it brings an error 
```shell
$~ require github.com/umee-network/umee/v2: version "v3.0.0-xxx" invalid: should be v2, not v3
```

A clear and concise description of what the 🐞 is.

## Version

Please provide the output of the following commands:

- `$ umeed version`
- `$ go version`
- `$ uname -a`

## Steps to Reproduce

1. ...

```shell
$~ go install github.com/umee-network/umee/price-feeder@v3.0.0-alpha2 
$~ make build
```

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by robert-zaremba** [comment] 2022-08-25 12:37
Duplicate of: https://github.com/orgs/umee-network/projects/8/views/2

**Closed by robert-zaremba** 2022-08-25 12:37 UTC
Labels: P:High

**Comment by RafilxTenfen** [comment] 2022-08-25 16:02
@robert-zaremba it was not an issue yet '-'
